### ISSUE TITLE
segfault when generating truetype/opentype fonts

### ISSUE THREAD

**Issue by cbaakman** [fontforge/fontforge#2726]
On fontforge 14:57 GMT 31-jul-2012 version,

for a particular fontforge file, a segfault always occurs when I try to generate truetype fonts or other formats. SVG fonts still work however.

The SFD file contains glyphs for latin as well as non-latin characters and references are also used. Furthermore, it has a horizontal kern-by-classes table.

If there's a mistake in my font setup, I'd like to know what it is so that I can correct it, rather than getting a segfault.

If you (the developer) need the SFD file, I could send it.

**Comment by JoesCat** [comment]
There are over 9800 patches and updates added to FontForge of 2012 and the current HEAD, some of them minor, some fairly major.
Please try a more recent version first.

**Comment by cbaakman** [comment]
OK sorry about that! I thought the apt-get version was the latest stable.

Yesterday (19th of may 2016, evening) I built the most recent master branch version on ubuntu 14.
It has the same segfault however.

**Comment by JoesCat** [comment]
I'm way overloaded with other things that need doing and hope someone else has the time to look at this, ...however, best to send a copy. If it needs to be private, zip it, and you can find my email in the git logs, or my profile page. If it can be posted for anyone, you'll potentially have more eyes looking at it.

**Comment by JoesCat** [comment]
Hi @cbaakman,
Okay, I tried:
File->Generate Fonts.
NOTE: I do have checked-on = "Validate before saving"
I then selected ttf and then pressed "Generate" (ttf file)

Results:
"The font contains errors
Self intersecting
Wrong direction
Missing Points at Extrema
Would you like to review the errors or save the font anyways?

Yes - Review (results):
I noted 40 errors that require fixing.
All errors show "Missing Points at Extrema"

I tried this again with "Validate before saving" turned-off this time.
and it creates segfault.

Right now, the easiest/quickest fix for me would be to simply refuse saving without having all the problems with this font fixed first. This means you (and everyone else) would be forced to fix their errors before being able to export a bad ttf file. Before I add such a fix, I'd rather understand and go through this code in more detail. So at this point it's considered won't fix yet, plus a bad font file that needs fixing first.

From your point of view, turn on the check "Validate before saving", and please fix all errors listed until you have zero errors listed. After you have fixed all the errors listed, and if this font file still creates a segfault, I'd like to check again, but before this point in time, it's too early for me to do anything with this yet.

**Comment by cbaakman** [comment]
OK! I'll fix all these errors and try again. However, normally fontforge doesn't segfault over non-integral coordinates and missing points at extrema. Also, the documentation says it's recommended for truetype to have integral coordinates, not that fontforge needs it.

**Comment by jtanx** [comment]
To be honest, regardless of the font validation, it's not good behaviour if FontForge is segfaulting when saving the file. So I would classify this as a bug and not as being invalid.

**Comment by cbaakman** [comment]
I've corrected the problems and it passes the validation. However, forntorge still reports intersecting paths that don't show up in the validation.

**Comment by JoesCat** [comment]
Thanks for fixing the errors, it removed 3 drawing errors.
The problem is happening in tottf.c, and there is an uninitialized utf8name string getting passed into AddEncodedName().

at about this location, I added a printf
```c
    ne->offset   = ftell(nt->strings);
//printf("value %d, %d\n",strid,lang);
    ne->len      = 2*utf82u_strlen(utf8name);
    dumpustr(nt->strings,utf8name);
```
and the program fell-over at 1034.
Looking at tottf.c there are a lot of routines with zero to non-existent error checks, but timewise I've got to get other stuff done right now. tottf.c needs a careful look and fixing!!!

**Comment by JoesCat** [comment]
...adding a minor link https://github.com/JoesCat/fontforge/tree/issue2726_2 but NOTE this is not a fix for the NULL utf8 value mentioned above...

**Comment by JoesCat** [comment]
Adding more info as to where the bug/error is coming from (using valgrind):
```c
==21287== Process terminating with default action of signal 11 (SIGSEGV)
==21287==  Access not within mapped region at address 0x0
==21287==    at 0x48DA5C4: AddEncodedName.part.15 (tottf.c:3767)
==21287==    by 0x48E7763: initATTables (tottf.c:3868)
==21287==    by 0x48E8DF4: initTables (tottf.c:5754)
==21287==    by 0x48E91B4: _WriteTTFFont (tottf.c:6105)
==21287==    by 0x48E98D4: WriteTTFFont (tottf.c:6138)
==21287==    by 0x47CE884: _DoSave (savefont.c:823)
==21287==    by 0x41A927D: DoSave (savefontdlg.c:1542)
==21287==    by 0x41AA4D1: GFD_exists (savefontdlg.c:1596)
==21287==    by 0x463B2E7: _gio_file_statfile (giofile.c:187)
==21287==    by 0x463B538: _GIO_localDispatch (giofile.c:240)
==21287==    by 0x463AAEC: GIOdispatch (gio.c:176)
==21287==    by 0x41AA5E8: _GFD_SaveOk (savefontdlg.c:1611)
```

**Comment by frank-trampe** [comment]
Hi, guys. Do we still have this file? I want to fix the actual crash at some point.

**Comment by cbaakman** [comment]
Today I rebuilt fontforge from the master branch. With this build, the segfault no longer occurs. The generated font seems fine. Did you find the bug?

**Comment by JoesCat** [comment]
Your bug had a fairly difficult path to follow (from my point of view), and 
sometimes the bugs are found indirectly, or affects something else which is 
easier to identify. If nobody claims it, then this is a possible reason to 
it getting fixed without having given it direct attention.

FYI - A couple of us tend to hit the easier bugs (where nobody 
complains/issues/identifies it as bugs), and it helps make the more difficult 
ones shallow(er) in difficulty, or extinguish them altogether.
I've seen categories of issues vaporize this way (nobody complains about X 
or Y anymore).

**Comment by skef** [comment]
We don't have the file that caused the problem and the filer of the issue indicated it did not reproduce. Closing, will reopen if needed.
